<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <Configurations>Debug;NoResources;Release;ReleaseOfficial;WIX</Configurations>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>TestKey.snk</AssemblyOriginatorKeyFile>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyTitle>chocolatey.tests</AssemblyTitle>
    <Product>chocolatey.tests</Product>
    <Copyright>Copyright ©  2012 - Present</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'NoResources|AnyCPU'">
    <OutputPath>bin\NoResources\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ReleaseOfficial|AnyCPU'">
    <OutputPath>bin\ReleaseOfficial\</OutputPath>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Build" />
    <PackageReference Include="Chocolatey.NuGet.Commands" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Common" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Configuration" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Credentials" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.DependencyResolver.Core" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Frameworks" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.LibraryModel" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.PackageManagement" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Packaging" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.ProjectModel" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Protocol" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Resolver" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Versioning" Version="3.4.3" />
    <PackageReference Include="FluentAssertions" Version="6.11.0" />
    <PackageReference Include="FluentAssertions.Analyzers" Version="0.19.1" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Web.Xdt" Version="3.1.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="SimpleInjector" Version="3.3.2" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="2.2.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.8.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\chocolatey\chocolatey.csproj" />
    <ProjectReference Include="..\chocolatey.console\chocolatey.console.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="..\packages\FluentAssertions.Analyzers.0.19.1\analyzers\dotnet\cs\FluentAssertions.Analyzers.dll" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\SampleResource.txt" />
  </ItemGroup>
</Project>