<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <WarningsAsErrors>CA1416</WarningsAsErrors>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>false</UseWindowsForms>
    <ImportWindowsDesktopTargets>false</ImportWindowsDesktopTargets>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\chocolatey.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DebugSymbols>true</DebugSymbols>
    <DocumentationFile>bin\Release\chocolatey.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>..\..\docs\logo\chocolatey.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'NoResources|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\NoResources\</OutputPath>
    <DefineConstants>TRACE;NoResources</DefineConstants>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DocumentationFile>bin\Release\chocolatey.xml</DocumentationFile>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ReleaseOfficial|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\ReleaseOfficial\</OutputPath>
    <DefineConstants>TRACE;FORCE_CHOCOLATEY_OFFICIAL_KEY</DefineConstants>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DocumentationFile>bin\Release\chocolatey.xml</DocumentationFile>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Rhino.Licensing">
      <HintPath>..\..\lib\Rhino.Licensing.1.4.1\lib\net40\Rhino.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Security" />
    <Reference Include="System.Transactions" />
    <Reference Include="System.Windows" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SolutionVersion.cs">
      <Link>Properties\SolutionVersion.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.config.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure.app\configuration\chocolatey.config">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\docs\logo\chocolatey.ico">
      <Link>Properties\chocolatey.ico</Link>
    </None>
  </ItemGroup>
  <Choose>
    <When Condition=" '$(Configuration)' != 'NoResources' ">
      <ItemGroup>
        <ProjectReference Include="..\chocolatey.resources\chocolatey.resources.csproj">
          <Project>{AF584111-FE32-448D-A1D0-63217AF8B43C}</Project>
          <Name>chocolatey.resources</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
  </Choose>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.nocolor.config.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.mono.config.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.mono.nocolor.config.xml" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="BannedSymbols.txt" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.3.5" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="7.0.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AlphaFS" Version="2.3.0-dev-221109-0007" />
    <PackageReference Include="Chocolatey.NuGet.Commands" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Common" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Configuration" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Credentials" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.DependencyResolver.Core" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Frameworks" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.LibraryModel" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.PackageManagement" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Packaging" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.ProjectModel" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Protocol" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Resolver" Version="3.3.0" />
    <PackageReference Include="Chocolatey.NuGet.Versioning" Version="3.3.0" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.Web.Xdt" Version="3.1.0" />
    <PackageReference Include="SimpleInjector" Version="3.3.2" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="7.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Federation" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>