<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <OutputType>Library</OutputType>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Configurations>Debug;NoResources;Release;ReleaseOfficial;WIX</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\docs\logo\chocolatey.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\chocolatey.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DebugSymbols>true</DebugSymbols>
    <DocumentationFile>bin\Release\chocolatey.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'NoResources|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\NoResources\</OutputPath>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DocumentationFile>bin\Release\chocolatey.xml</DocumentationFile>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ReleaseOfficial|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\ReleaseOfficial\</OutputPath>
    <DefineConstants>TRACE;FORCE_CHOCOLATEY_OFFICIAL_KEY</DefineConstants>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DocumentationFile>bin\Release\chocolatey.xml</DocumentationFile>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Build" />
    <PackageReference Include="AlphaFS" Version="2.3.0-dev-221109-0007" />
    <PackageReference Include="Chocolatey.NuGet.Commands" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Common" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Configuration" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Credentials" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.DependencyResolver.Core" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Frameworks" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.LibraryModel" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.PackageManagement" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Packaging" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.ProjectModel" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Protocol" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Resolver" Version="3.4.3" />
    <PackageReference Include="Chocolatey.NuGet.Versioning" Version="3.4.3" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.3" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.6.0-preview.5 " />
    <PackageReference Include="Microsoft.Web.Xdt" Version="3.1.0" />
    <PackageReference Include="Rhino.Licensing" Version="1.6.0-alpha-20240531" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SimpleInjector" Version="3.3.2" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="2.2.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.8.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SolutionVersion.cs">
      <Link>Properties\SolutionVersion.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.config.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure.app\configuration\chocolatey.config">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\docs\logo\chocolatey.ico">
      <Link>Properties\chocolatey.ico</Link>
    </None>
  </ItemGroup>
  <Choose>
    <When Condition=" '$(Configuration)' != 'NoResources' ">
      <ItemGroup>
        <ProjectReference Include="..\chocolatey.resources\chocolatey.resources.csproj">
          <Project>{AF584111-FE32-448D-A1D0-63217AF8B43C}</Project>
          <Name>chocolatey.resources</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
  </Choose>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.nocolor.config.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.mono.config.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="infrastructure\logging\log4net.mono.nocolor.config.xml" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="BannedSymbols.txt" />
  </ItemGroup>
</Project>