FROM mono:6.12

MAINTAINER Justin Phelps <linuturk@onitato.com>

RUN apt-get update && apt-get install git -y

COPY . /usr/local/src/choco/

WORKDIR /usr/local/src/choco
RUN chmod +x build.sh
RUN chmod +x zip.sh
RUN ./build.sh

WORKDIR /opt
RUN cp -r /usr/local/src/choco/code_drop/chocolatey/console /opt/chocolatey && mkdir /opt/chocolatey/lib

COPY docker/choco_wrapper /usr/local/bin/choco
COPY docker/choco_wrapper /usr/local/bin/choco.exe

ENV ChocolateyInstall /opt/chocolatey

WORKDIR /root
