<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;NoResources;Release;ReleaseOfficial;WIX</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ReleaseOfficial|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\ReleaseOfficial\</OutputPath>
    <DefineConstants>TRACE;FORCE_CHOCOLATEY_OFFICIAL_KEY</DefineConstants>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.6.0-preview.5 " />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\chocolatey\StringResources.cs">
      <Link>Shared\StringResources.cs</Link>
    </Compile>
    <Compile Include="..\SolutionVersion.cs">
      <Link>Properties\SolutionVersion.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Chocolatey.PowerShell.dll-Help.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>