name: Chocolatey Builds

on:
  # Trigger on pushes to master and develop, or with pull requests
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build using mono on Ubuntu
  ubuntu-build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Build with Mono
      run: |
        chmod +x build.sh
        $GITHUB_WORKSPACE//build.sh -v
    - name: Setup tmate
      uses: mxschmitt/action-tmate@v3.7
      with:
        limit-access-to-actor: true
    - name: Test with Nunit on Mono
      run: $GITHUB_WORKSPACE//test.sh full
  # Build on Windows
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with .Net Framework
      run: .\build.bat -v
    - name: Test with Nunit on .Net Framework
      run: .\test.bat full